### ISSUE TITLE
Drupal.org

### ISSUE THREAD

**Issue by nickschuch** [mrhanlon/log_stdout#1]
Hi!

I was wondering if you would be interesting in putting this module up on drupal.org so it gets drush integration.

If your not interested it putting it up would you be happy if I used this code as a base?

Nick

**Comment by mrhanlon** [comment]
Sure thing: https://www.drupal.org/project/log_stdout. I would prefer to continue using Github for development and will mirror to Drupal.org.

**Comment by nickschuch** [comment]
No worries at all! Thanks @mrhanlon
